version: 0.1.0                                            

name: Deploy a Django app to Azure
description: A stack to deploy a Django based website to Azure app service               

branding:                                                # stack branding 
 icon: 'package'
 color: 'black'

inputs:
  - name: AZURE_CREDENTIALS
    description: Azure cred
    required: true
    is-secret: true
  - name: CREATE_AZURE_WEBAPP
    required: true
    default: 'yes'
    description: Need help in creating Azure web app? yes/no
  - name: AZURE_RESOURCE_GROUP_NAME
    required: true
    is-secret: true
    description: Name of the resource group
  - name: AZURE_WEBAPP_NAME
    description: Azure web app name
    required: true
    is-secret: true

configs:
  repo-metadata:
    parameters:
      description: 'Django app on Azure'
      secrets:
      - name: AZURE_CREDENTIALS
        value: ${{inputs.AZURE_CREDENTIALS}}
      - name: AZURE_WEBAPP_NAME
        value: ${{inputs.AZURE_WEBAPP_NAME}}
      - name: AZURE_RESOURCE_GROUP_NAME
        value: ${{inputs.AZURE_RESOURCE_GROUP_NAME}}
      topics:
      - django
      - azure

  branches:
    - name: main
      parameters:
        enforce-admins: true

  environments:
    - name: development
      parameters:
        protected-branches: false
        allowed-branch-rules:
          - main
          - releases/*
github-apps:
  - slug: AWS
init:
  uses: "stack-init.yaml"
